#!groovy

pipeline {

  agent any

 environment {
    GIT_URL = "ssh://git@153.126.152.131:45345/var/git/jenkinsfiles/ansible-configs/app/redmine"
  }

  parameters {
    string(
      name: 'GIT_BRANCHES',
      defaultValue: '*/master',
      description: "Git branch or tag name or commit id of GIT_URL of Jenkins job configuration file"
    )
  }

  stages {
    stage('Create backup') {
      steps {
        build job: 'ansible/playbook',
          parameters: [
                        string(
                          name: 'CONFIG_FILE_PATH',
                          value: "create-backup/config.yml"
                        ),
                        string(
                          name: 'GIT_BRANCHES',
                          value: "${params.GIT_BRANCHES}"
                        ),
                        string(
                          name: 'GIT_URL',
                          value: "${env.GIT_URL}"
                        ),
                        string(
                          name: 'WORKING_DIR',
                          value: "jeknins_job_app_redmine_create-backup"
                        )
                      ]
      }
    }
  }
}
